export enum AuditAction {
  // Payment Actions
  PAYMENT_INTENT_CREATED = "PAYMENT_INTENT_CREATED",
  PAYMENT_NOTIFICATION_RECEIVED = "PAYMENT_NOTIFICATION_RECEIVED",
  PAYMENT_SUCCEEDED = "PAYMENT_SUCCEEDED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_REFUNDED = "PAYMENT_REFUNDED",
  PAYMENT_NOTIFICATION_ERROR = "PAYMENT_NOTIFICATION_ERROR",

  // Subscription Actions
  SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_UPDATED = "SUBSCRIPTION_UPDATED",
  SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED",
  SUBSCRIPTION_RENEWED = "SUBSCRIPTION_RENEWED",
  SUBSCRIPTION_STATUS_CHANGED = "SUBSCRIPTION_STATUS_CHANGED",

  // User Actions
  USER_LOGIN = "USER_LOGIN",
  USER_LOGIN_FAILED = "USER_LOGIN_FAILED",
  USER_REGISTERED = "USER_REGISTERED",
  USER_REGISTERED_FAILED = "USER_REGISTERED_FAILED", // Añadido para registros fallidos
  USER_PASSWORD_RESET_REQUESTED = "USER_PASSWORD_RESET_REQUESTED",
  USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED",
  USER_EMAIL_VERIFIED = "USER_EMAIL_VERIFIED",
  USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED",
  USER_DELETED = "USER_DELETED",

  // CV Actions
  CV_CREATED = "CV_CREATED",
  CV_UPDATED = "CV_UPDATED",
  CV_DELETED = "CV_DELETED",
  CV_SHARED = "CV_SHARED",

  // Cover Letter Actions
  COVER_LETTER_CREATED = "COVER_LETTER_CREATED",
  COVER_LETTER_UPDATED = "COVER_LETTER_UPDATED",
  COVER_LETTER_DELETED = "COVER_LETTER_DELETED",

  // API Token Actions
  API_TOKEN_CREATED = "API_TOKEN_CREATED",
  API_TOKEN_DELETED = "API_TOKEN_DELETED",

  // General/System Actions
  ADMIN_ACTION = "ADMIN_ACTION", // For generic admin operations
  SYSTEM_ERROR = "SYSTEM_ERROR",
}
